### ISSUE TITLE
.NET 4.5 upgrade

### ISSUE THREAD

**Issue by sambengtson** [soitgoes/LoveSeat#61]
I'm having a little trouble upgrading the VS project to .NET 4.5.  It seems to build ok but when I reference it from another project and run it, i run into a TypeLoadException.  

Normally, I would associate this to a framework mismatch, but LoveSeat, and my other project are both .NET 4.5.  Is it possible that the issue lies with  libcurl.dll and the other LoveSeat dependencies?

Thanks

**Comment by soitgoes** [comment]
Make sure that it's not just the installer.   I'm intentionally keeping it
in 3.5 so that we have compatibility.  You should be able to reference it
in your 4.5 project even as a 3.5

What's the reason for the upgrade?

On Thu, Mar 19, 2015 at 2:51 PM, Sam <notifications@github.com> wrote:

> I'm having a little trouble upgrading the VS project to .NET 4.5. It seems
> to build ok but when I reference it from another project and run it, i run
> into a TypeLoadException.
>
> Normally, I would associate this to a framework mismatch, but LoveSeat,
> and my other project are both .NET 4.5. Is it possible that the issue lies
> with libcurl.dll and the other LoveSeat dependencies?
>
> Thanks
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/soitgoes/LoveSeat/issues/61>.
>



-- 
Martin Murphy
Whiteboard-IT
http://whiteboard-it.com
w: (205) 588-7102

**Comment by sambengtson** [comment]
Looks like I got it working by leaving it a 3.5 project.  Not sure what happened there.  Maybe I ran into a compatibility issue.  Sorry about that!
